### ISSUE TITLE
Support providing a list of source names and urls.

### ISSUE THREAD

**Issue by AraHaan** [fabriciomurta/ensure-nuget-source#1]
I would like it if the action allowed passing in multiple source names and urls as a list to ensure they are added before build.

This is useful if the build depends on multiple sources, not just the nuget.org source where some dependencies might not be a part of. Yes, while the project has a nuget.config file, I would prefer also setting up the action with all of them in case something breaks and nuget refuses to pick up my config file and use it on top of the default one for github actions.

I also randomly got bit by the nuget.org source randomly disappearing in some runs as well too, which is why I want to be able to ensure that all sources I expect to be added *before* restore and build are added.

**Comment by fabriciomurta** [comment]
That's pretty possible, but lots of scenarios to test.

Actually, you can currently have this one if you just set up to several steps. If you don't have an extensive list of sources, this should work out of the box for you.

```yaml
- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'nuget.org'
    url: 'https://api.nuget.org/v3/index.json'

- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'backup source'
    url: 'https://api.mybackupsource.org/v3/index.json'

- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'local source 2'
    url: '${{ github.workspace }}/local_nuget_repo'
```

Some issues you may find is having conflicting/mismatching `names` and `urls` (if the URL is not found but the `name` is, then it will replace whatever is in the existing source `name` with the specified `url`.

If you do something like this:
```yaml
- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'nuget.org'
    url: 'https://api.nuget.org/v3/index.json'

- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'nuget.org'
    url: 'https://api.mybackupsource.org/v3/index.json'
```

You'll end up replacing `nuget.org` source with your backup source address.

Another potential issue is, when you provide a local path, the added source appends the current path, so two sequential runs of the same action would try to fix the path in this case:

```yaml
- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'backup source'
    url: 'my_local_repo'

- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    name: 'backup source'
    url: 'my_local_repo'
```

And the second may fail if using a different `name`, because it will not find the just-added source and will try to re-add it -- which the `dotnet nuget` tool would probably return as error.

In general, you should be safe with the repeated steps of the action if you keep these edge cases in mind.

**Comment by AraHaan** [comment]
I would prefer to have this instead of replicating it:

like for example I could then have:

```yml
- uses: fabriciomurta/ensure-nuget-source@v1
  with:
    list: # list of sources to use.
      - name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'
      - name: 'My local package builds'
        url: 'artifacts' # sub-directory of the repository root.
      - name: 'dotnet-core'
        url: 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json'
      - name: 'dotnet5'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json'
      - name: 'dotnet5-transport'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json'
      - name: 'dotnet6'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json'
      - name: 'dotnet6-transport'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json'
      - name: 'dotnet-public'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json'
      - name: 'dotnet-eng'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
      - name: 'dotnet-tools'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
      - name: 'dotnet-tools-transport'
        url: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-transport/nuget/v3/index.json'
      - name: 'xunit-prereleases'
        url: 'https://www.myget.org/F/xunit/api/v3/index.json'
```

Just because many people (myself included) prefer as few build steps as possible to make the workflows more readable.

Or at least some way to set the list with an user defined amount of sources to use.
